### ISSUE TITLE
Checksum for cpsid_52915 file chf8010004.zip is not correct!

### ISSUE THREAD

**Issue by walterbax** [AboutWebLLC/unofficial-updater2#42]
not sure if I can bypass this, as I am running this on a 9.0.1 install, and that is a 8.0.1 hot fix.

here is my output/errors log from the gUI
http://pastebin.com/cyM8sFSc

**Comment by dcepler** [comment]
Just checked the file download from Adobe at http://helpx.adobe.com/content/dam/kb/en/529/cpsid_52915/attachments/chf8010004.zip and the SHA-512 hash matched the stored one in Unofficial Updater 2. Try running UU2 again to try and download the file again.

**Comment by walterbax** [comment]
I have ran it a few times before posting, from the command line, from double clicking, and again just now, same error has occurred again. hm.

http://pastebin.com/h4QhpJx2

**Comment by dcepler** [comment]
Found the issue. Two things. First Adobe implemented an **http -> https** redirect for files coming from *helpx.adobe.com*. The second is that the get task in Ant does not properly follow HTTP 301 redirects, [Ant Bug #47433](https://bz.apache.org/bugzilla/show_bug.cgi?id=47433) which is causing the checksum to fail since the file is not getting written. The download has been updated with the corrected links to go directly to https. Please download Unofficial Updater 2 again and run it.
